version: 0.4.{build}
configuration: Release
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/cff271c9681834896234
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- nuget restore
build:
  project: Untappd.Net.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: normal
after_test:
- packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[Untappd.Net*]* -[*Tests]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  src\Untappd.Net.UnitTests\bin\Release\Untappd.Net.UnitTests.dll" -output:coverage.xml
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
- gem install bundle
- bundle
- rake cs_lint
deploy:
- provider: NuGet
  server:
  api_key:
    secure: fGNwXOtebe3kxu5SrB90CrbaCxVxuzuCQh3Ipcc0G/3cutoNZf7d7G6AaQ4fRv2l
  on:
    branch: release
- provider: NuGet
  server: https://www.myget.org/F/untappd-net/
  api_key:
    secure: wsN6BzH8ETiXhB9SndP57mHhivqM+CVnghI/+w5XE3bI8K092Z4V4FrJixcrxKnI
  on:
    branch: release
